### ISSUE TITLE
Epub Exception

### ISSUE THREAD

**Issue by adityanemali** [paulocheque/epub-meta#3]
Traceback (most recent call last):
  File "file.py", line 10, in <module>
    metadata = get_epub_metadata(str(filename),read_cover_image=True, read_toc=True)
  File "/home/hello/anaconda3/lib/python3.6/site-packages/epub_meta/collector.py", line 331, in get_epub_metadata
    raise EPubException('Unknown file')
epub_meta.exceptions.EPubException: Unknown file

**Comment by paulocheque** [comment]
```
    if not zipfile.is_zipfile(filepath):
        raise EPubException('Unknown file')
```
