### ISSUE TITLE
Exception when cover is not found

### ISSUE THREAD

**Issue by davidgfnet** [paulocheque/epub-meta#4]
Hey there!
Neat lib, thanks!

So I'm getting an error when a "probably malformed epub book" points to a non-existant cover file inside the epub zip. In particular an exception is raised at:

```content = zf.read(os.path.join(base_dir, filepath))```

I think it would be much better if the library handled this in some nice way, like, maybe setting all cover_image_* keys to None, or actually not creating them at all. I can send a pull request if you think it's acceptable.

Thanks again!

**Comment by paulocheque** [comment]
Hi, thanks for the report.

Is this `cover_image_*` part of some epub specification? if yes, I guess a PR would be perfect.

Otherwise, I don't think we should include verifications of invalid epub in the lib. Did you try parsing the XML file by yourself?

`print(get_epub_opf_xml('/path/to/my_epub_file.epub'))`

But one last question, is the zip file valid? Maybe it is using some specific compression that is not supported for the python library. If this is the case, it would be greate to support other zip formats.

**Comment by davidgfnet** [comment]
Hey. I think it is as simple as: this is a valid zip file that has some valid xml. The xml has a cover field that points to a non-existant jpg file in the zip. This might be something as simple as case sensitivity for example. I image something that might work on some platforms (say on windows, you extract the zip, parse the XML and everything works) but on some others (maybe linux, where Cover.jpg can't be found since the file name is really cover.jpg).
I guess I can mail you a few examples of such epub files.

**Comment by davidgfnet** [comment]
Hey there. More details about one particular book:

```
    <item href="images/cover.jpeg" id="cover" media-type="image/jpeg"/>
    <item href="images/img1.jpg" id="img1" media-type="image/jpeg"/>
    <item href="images/img2.jpg" id="img2" media-type="image/jpeg"/>
```

The ZIP file contains an Images/cover.jpeg file (note the uppercase).

There's two problems: Either we fix with this some magic or we just stop causing exceptions but not report a cover.

**Comment by davidgfnet** [comment]
This is the error I get:

```
Traceback (most recent call last):
  File "epub_index.py", line 86, in <module>
    metadata = epub_meta.get_epub_metadata(f, read_cover_image=True, read_toc=True)
  File "/usr/lib/python2.7/site-packages/epub_meta-0.0.6-py2.7.egg/epub_meta/collector.py", line 377, in get_epub_metadata
    cover_image_content, cover_image_extension = _discover_cover_image(zf, opf_xmldoc, opf_filepath)
  File "/usr/lib/python2.7/site-packages/epub_meta-0.0.6-py2.7.egg/epub_meta/collector.py", line 203, in _discover_cover_image
    content = zf.read(os.path.join(base_dir, filepath))
  File "/usr/lib64/python2.7/zipfile.py", line 935, in read
    return self.open(name, "r", pwd).read()
  File "/usr/lib64/python2.7/zipfile.py", line 961, in open
    zinfo = self.getinfo(name)
  File "/usr/lib64/python2.7/zipfile.py", line 909, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named u'OEBPS/images/cover.jpeg' in the archive"
```

**Comment by mcepl** [comment]
Yeah, the same here:
```
~@stitny$ epubgrep -i 'And so I responded in kind' ~/Knihy/**/*.epub
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/matej/archiv/2018/projekty/epubgrep/epubgrep.py", line 40, in grep_book
    metadata = epub_meta.get_epub_metadata(filename)
  File "/home/matej/.local/lib/python3.8/site-packages/epub_meta/collector.py", line 388, in get_epub_metadata
    cover_image_content, cover_image_extension = _discover_cover_image(zf, opf_xmldoc, opf_filepath)
  File "/home/matej/.local/lib/python3.8/site-packages/epub_meta/collector.py", line 212, in _discover_cover_image
    content = zf.read(coverpath)
  File "/usr/lib64/python3.8/zipfile.py", line 1475, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/lib64/python3.8/zipfile.py", line 1514, in open
    zinfo = self.getinfo(name)
  File "/usr/lib64/python3.8/zipfile.py", line 1441, in getinfo
    raise KeyError(
KeyError: "There is no item named 'OEBPS/cover.jpg' in the archive"
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matej/.local/bin/epubgrep", line 11, in <module>
    load_entry_point('epubgrep', 'console_scripts', 'epubgrep')()
  File "/home/matej/archiv/2018/projekty/epubgrep/epubgrep.py", line 141, in main
    data = future.result()
  File "/usr/lib64/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib64/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
KeyError: "There is no item named 'OEBPS/cover.jpg' in the archive"
~@stitny$ 
```
Could we at least get `EPubException`, so I don’t have to hunt all possible exceptions which may happen in this situation?

**Comment by paulocheque** [comment]
Hey there, I am not free to mantain this library right now. If you publish a PR I will be happy to merge it.

**Comment by mcepl** [comment]
@paulocheque You got it.

**Comment by davidgfnet** [comment]
Perhaps not as complete but I'd like to keep maintaining it in the future and adding features, I created this a few weeks ago:
https://github.com/davidgfnet/epubinfo
